services:
  ytdlp:
    # build:
    #   context: .
    #   dockerfile: dockerfile
    image: zhangyiming748/stand:v0.1.3
    container_name: ytdlp
    volumes:
      - ./:/data
    command: top
    environment:
      - PROXY=http://192.168.5.115:8889